
let TYPES = {
    USER_DATA: "USER_DATA",
    CHANNEL_DATA: 'CHANNEL_DATA',
    CHANNEL_SELECT: 'CHANNEL_SELECT',
    MESSAGE_DATA: 'MESSAGE_DATA',
    USER_DISCONNECT: 'USER_DISCONNECT',
    USER_UPDATE: 'USER_UPDATE'
}

export default TYPES